# Generated by Django 3.2.5 on 2021-07-06 11:31

import django.core.validators
from django.db import migrations, models
import students.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_no', models.CharField(default=students.models.get_default_reg_no, help_text='Student id', max_length=20)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('first_name', models.CharField(help_text='First name', max_length=150)),
                ('middle_name', models.CharField(blank=True, help_text='Middle name', max_length=150, null=True)),
                ('last_name', models.CharField(help_text='Last name', max_length=150)),
                ('degree', models.CharField(choices=[('btech', 'B.Tech'), ('mtech', 'M.Tech'), ('phd', 'PhD')], help_text='Passing degree', max_length=10)),
                ('department', models.CharField(blank=True, choices=[('ape', 'APE'), ('fmp', 'FMP'), ('ide', 'IDE'), ('swce', 'SWCE')], help_text='Department', max_length=10, null=True)),
                ('reg_year', models.IntegerField(default=2021, help_text='Registration year', validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2021)])),
                ('pass_year', models.IntegerField(default=2021, help_text='Graduation year', validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2021)])),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True)),
            ],
            options={
                'verbose_name': 'Registered Student',
                'verbose_name_plural': 'Registered Students',
                'ordering': ['reg_no', 'birth_date', 'first_name', 'last_name'],
                'unique_together': {('reg_no', 'degree', 'reg_year')},
            },
        ),
    ]
