# Generated by Django 3.2.5 on 2021-07-09 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['reg_no', 'last_name', 'first_name', 'middle_name', 'birth_date'], 'verbose_name': 'Registered Student', 'verbose_name_plural': 'Registered Students'},
        ),
    ]
