MAIN_SECTOR = [
    'Government',
    'Private',
    'NGO',
    'Entrepreneur',
    'Farmer',
    'Student',
    'Other',
]

SUBSECTOR = [
    'Central Government',
    'IAS',
    'IPS',
    'IFoS',
    'Other UPSC Services',
    'ICAR',
    'State-Agriculture',
    'State-Forestry',
    'State-Revenue',
    'State-Police',
    'State-Cooperatives',
    'State-Corporations',
    'State-Other bodies',
    'Mantralaya',
    'Agriculture Universities',
    'Non Agricultural Universities',
    'Private College',
    'KVK',
    'NGO',
    'Dealer/Distributor',
    'Industrialist',
    'LIC',
    'IIT',
    'NIT',
    'IIM',
    'Freelancing',
    'Consultant',
    'Other',
]

SKILLS = [
    'Administration',
    'Irrigation & Water Management',
    'Protected Cultivation',
    'Energy',
    'Food & Fruit Processing',
    'Farm Machinery',
    'Watershed Management',
    'Information Technology',
    'Remote Sensing',
    'GIS',
    'Internet of Things',
    'Drones',
    'Robotics',
    'Precision Agriculture',
    'Environment',
    'Dairy',
    'Poultry',
    'Fishery',
    'Insurance',
    'Banking',
    'Finance',
    'Taxes',
    'Construction',
    'Farming',
    'Other'

]
